name: matrix2markers
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - snakemake
  - scanpy
  - anndata
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - harmonypy
  - leidenalg
  - pip
  - pip:
    - scrublet
    - scikit-misc